version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

workflows:
  version: 2
  apply_infra:
    jobs:
      - terraform/validate:
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          requires:
            - terraform/plan
